#ifndef WEEKDAY_H
#define WEEKDAY_H

#include <string>

// Another part of the program will need to implement "incrementWeekday()".
// - Maybe it could be "const std::string &nextWeekday(const std::string &weekdayName)".

// A list of weekday strings can be generated by reading from the Arena executable.

class Weekday
{
private:
	std::string weekdayName;
public:
	Weekday(const std::string &weekdayName);
	~Weekday();

	// This isn't really a necessary value, because weeks themselves are unnamed,
	// but it's in the manual, so it's here for completeness.
	static const int DAYS_PER_WEEK;

	const std::string &getWeekdayName() const;
};

#endif
