#include <cassert>
#include <map>

#include "Location.h"

#include "ClimateName.h"
#include "LocationType.h"
#include "ProvinceName.h"

// This data isn't required to be in the source file. An enumeration for each location
// is nice to have, but it's not necessary, either. All that's needed is to group
// locations by province, and treat them as an "individual data item" with all the
// associated members like name, climate, etc..

// The displayed name for each map location.
const auto LocationDisplayNames = std::map<LocationName, std::string>
{
	// Black Marsh.
	{ LocationName::AltenCorimont, "Alten Corimont" },
	{ LocationName::AltenMarkmont, "Alten Markmont" },
	{ LocationName::AltenMeirhall, "Alten Meirhall" },
	{ LocationName::Archon, "Archon" },
	{ LocationName::Blackrose, "Blackrose" },
	{ LocationName::Branchgrove, "Branchgrove" },
	{ LocationName::Branchmont, "Branchmont" },
	{ LocationName::Chasecreek, "Chasecreek" },
	{ LocationName::Chasepoint, "Chasepoint" },
	{ LocationName::Gideon, "Gideon" },
	{ LocationName::Glenbridge, "Glenbridge" },
	{ LocationName::Greenglade, "Greenglade" },
	{ LocationName::Greenspring, "Greenspring" },
	{ LocationName::Helstrom, "Helstrom" },
	{ LocationName::Lilmoth, "Lilmoth" },
	{ LocationName::Longmont, "Longmont" },
	{ LocationName::Moonmarch, "Moonmarch" },
	{ LocationName::PortdunMont, "Portdun Mont" },
	{ LocationName::Riverbridge, "Riverbridge" },
	{ LocationName::Riverwalk, "Riverwalk" },
	{ LocationName::Rockgrove, "Rockgrove" },
	{ LocationName::Rockguard, "Rockguard" },
	{ LocationName::Rockpark, "Rockpark" },
	{ LocationName::Rockpoint, "Rockpoint" },
	{ LocationName::Rockspring, "Rockspring" },
	{ LocationName::Seafalls, "Seafalls" },
	{ LocationName::Seaspring, "Seaspring" },
	{ LocationName::Soulrest, "Soulrest" },
	{ LocationName::Stonewastes, "Stonewastes" },
	{ LocationName::Stormhold, "Stormhold" },
	{ LocationName::TenmarWall, "Tenmar Wall" },
	{ LocationName::Thorn, "Thorn" },

	// Elsweyr.
	{ LocationName::Alabaster, "Alabaster" },
	{ LocationName::BlackHeights, "Black Heights" },
	{ LocationName::BrukreichBridge, "Brukreich Bridge" },
	{ LocationName::Chasegrove, "Chasegrove" },
	{ LocationName::Chasemoor, "Chasemoor" },
	{ LocationName::CoriDarglade, "Cori Darglade" },
	{ LocationName::Corinthe,  "Corinthe" },
	{ LocationName::DarkarnPlace, "Darkarn Place" },
	{ LocationName::DarvulkHaven, "Darvulk Haven" },
	{ LocationName::DuncoriWalk, "Duncori Walk" },
	{ LocationName::Dune, "Dune" },
	{ LocationName::EinMeirvale, "Ein Meirvale" },
	{ LocationName::Greenhall, "Greenhall" },
	{ LocationName::HeimthorMount, "Heimthor Mount" },
	{ LocationName::HelkarnLand, "Helkarn Land" },
	{ LocationName::KingsWalk, "KingsWalk" },
	{ LocationName::MarkgranBrook, "Markgran Brook" },
	{ LocationName::MeirLynmount, "Meir Lynmount" },
	{ LocationName::NeumarWalk, "Neumar Walk" },
	{ LocationName::Orcrest, "Orcrest" },
	{ LocationName::PortneuView, "Portneu View" },
	{ LocationName::Rimmen, "Rimmen" },
	{ LocationName::Riverhold, "Riverhold" },
	{ LocationName::RiverKeep, "River Keep" },
	{ LocationName::Seaplace, "Seaplace" },
	{ LocationName::Senchal, "Senchal" },
	{ LocationName::SouthGuard, "South Guard" },
	{ LocationName::TardornWood, "Tardorn Wood" },
	{ LocationName::TenmarForest, "Tenmar Forest" },
	{ LocationName::Torval, "Torval" },
	{ LocationName::ValleyGuard, "Valley Guard" },
	{ LocationName::VerkarthHills, "Verkarth Hills" },

	// Hammerfell.
	{ LocationName::BelkarthGuard, "Belkarth Guard" },
	{ LocationName::Chaseguard, "Chaseguard" },
	{ LocationName::Chasetown, "Chasetown" },
	{ LocationName::CliffKeep, "Cliff Keep" },
	{ LocationName::CortenMont, "Corten Mont" },
	{ LocationName::DragonGate, "Dragon Gate" },
	{ LocationName::DragonGrove, "Dragon Grove" },
	{ LocationName::Dragonstar, "Dragonstar" },
	{ LocationName::Elinhir, "Elinhir" },
	{ LocationName::Gilane, "Gilane" },
	{ LocationName::Hegathe, "Hegathe" },
	{ LocationName::HeldornMount, "Heldorn Mount" },
	{ LocationName::KarnverFalls, "Karnver Falls" },
	{ LocationName::LainebonPlace, "Lainebon Place" },
	{ LocationName::Lainlyn, "Lainlyn" },
	{ LocationName::NimbelMoor, "Nimbel Moor" },
	{ LocationName::NorthHall, "North Hall" },
	{ LocationName::Rihad, "Rihad" },
	{ LocationName::Riverpoint, "Riverpoint" },
	{ LocationName::Riverview, "Riverview" },
	{ LocationName::Roseguard, "Roseguard" },
	{ LocationName::Sentinel, "Sentinel" },
	{ LocationName::Shadymarch, "Shadymarch" },
	{ LocationName::Skaven, "Skaven" },
	{ LocationName::Stonedale, "Stonedale" },
	{ LocationName::Stonemoor, "Stonemoor" },
	{ LocationName::Sunkeep, "Sunkeep" },
	{ LocationName::Taneth, "Taneth" },
	{ LocationName::ThorstadPlace, "Thorstad Place" },
	{ LocationName::VerkarthCity, "Verkarth City" },
	{ LocationName::VulkneuTown, "Vulkneu Town" },
	{ LocationName::VulnimGate, "Vulnim Gate" },

	// High Rock.
	{ LocationName::BlackWastes, "Black Wastes" },
	{ LocationName::Camlorn, "Camlorn" },
	{ LocationName::CloudSpring, "Cloud Spring" },
	{ LocationName::Daggerfall, "Daggerfall" },
	{ LocationName::DunkarnHaven, "Dunkarn Haven" },
	{ LocationName::DunlainFalls, "Dunlain Falls" },
	{ LocationName::EagleBrook, "Eagle Brook" },
	{ LocationName::EbonWastes, "Ebon Wastes" },
	{ LocationName::Evermore, "Evermore" },
	{ LocationName::Farrun, "Farrun" },
	{ LocationName::Glenpoint, "Glenpoint" },
	{ LocationName::IlessenHills, "Ilessen Hills" },
	{ LocationName::Jehanna, "Jehanna" },
	{ LocationName::KarthgranVale, "Karthgran Vale" },
	{ LocationName::KingsGuard, "Kings Guard" },
	{ LocationName::MarkwastenMoor, "Markwasten Moor" },
	{ LocationName::MeirDarguard, "Meir Darguard" },
	{ LocationName::MeirThorvale, "Meir Thorvale" },
	{ LocationName::Moonguard, "Moonguard" },
	{ LocationName::NormarHeights, "Normar Heights" },
	{ LocationName::NorthPoint, "North Point" },
	{ LocationName::NorvulkHills, "Norvulk Hills" },
	{ LocationName::OldGate, "Old Gate" },
	{ LocationName::PortdunCreek, "Portdun Creek" },
	{ LocationName::RavenSpring, "Raven Spring" },
	{ LocationName::ReichGradkeep, "Reich Gradkeep" },
	{ LocationName::Shornhelm, "Shornhelm" },
	{ LocationName::ThorkanPark, "Thorkan Park" },
	{ LocationName::VermeirWastes, "Vermeir Wastes" },
	{ LocationName::Wayrest, "Wayrest" },
	{ LocationName::WhiteHaven, "White Haven" },
	{ LocationName::WindKeep, "Wind Keep" },

	// Imperial Province.
	{ LocationName::ImperialCity, "Imperial City" },

	// Morrowind.
	{ LocationName::AmberForest, "Amber Forest" },
	{ LocationName::Blacklight, "Blacklight" },
	{ LocationName::CorkarthRun, "Corkarth Run" },
	{ LocationName::CormarView, "Cormar View" },
	{ LocationName::DarnimWatch, "Darnim Watch" },
	{ LocationName::DragonGlade, "Dragon Glade" },
	{ LocationName::EagleMoor, "Eagle Moor" },
	{ LocationName::Ebonheart, "Ebonheart" },
	{ LocationName::Firewatch, "Firewatch" },
	{ LocationName::GlenHaven, "Glen Haven" },
	{ LocationName::Greenheights, "Greenheights" },
	{ LocationName::HeimlynKeep, "Heimlyn Keep" },
	{ LocationName::HelnimWall, "Helnim Wall" },
	{ LocationName::KarththorDale, "Karththor Dale" },
	{ LocationName::KarththorHeights, "Karththor Heights" },
	{ LocationName::Kragenmoor, "Kragenmoor" },
	{ LocationName::MarkgranForest, "Markgran Forest" },
	{ LocationName::Mournhold, "Mournhold" },
	{ LocationName::Narsis, "Narsis" },
	{ LocationName::Necrom, "Necrom" },
	{ LocationName::Oaktown, "Oaktown" },
	{ LocationName::OldKeep, "Old Keep" },
	{ LocationName::OldRun, "Old Run" },
	{ LocationName::ReichParkeep, "Reich Parkeep" },
	{ LocationName::Riverbridge2, "Riverbridge" },
	{ LocationName::SailenVulgate, "Sailen Vulgate" },
	{ LocationName::SilgradTower, "Silgrad Tower" },
	{ LocationName::SilnimDale, "Silnim Dale" },
	{ LocationName::Stonefalls, "Stonefalls" },
	{ LocationName::Stoneforest, "Stoneforest" },
	{ LocationName::Tear, "Tear" },
	{ LocationName::VerarchenHall, "Verarchen Hall" },

	// Skyrim.
	{ LocationName::AmberGuard, "Amber Guard" },
	{ LocationName::Amol, "Amol" },
	{ LocationName::BlackMoor, "Black Moor" },
	{ LocationName::Dawnstar, "Dawnstar" },
	{ LocationName::DragonBridge, "Dragon Bridge" },
	{ LocationName::DragonWood, "Dragon Wood" },
	{ LocationName::DunparWall, "Dunpar Wall" },
	{ LocationName::DunstadGrove, "Dunstad Grove" },
	{ LocationName::Falcrenth, "Falcrenth" },
	{ LocationName::Granitehall, "Granitehall" },
	{ LocationName::Greenwall, "Greenwall" },
	{ LocationName::HelarchenCreek, "Helarchen Creek" },
	{ LocationName::KarthwastenHall, "Karthwasten Hall" },
	{ LocationName::Lainalten, "Lainalten" },
	{ LocationName::LaintarDale, "Laintar Dale" },
	{ LocationName::MarkarthSide, "Markarth Side" },
	{ LocationName::NeugradWatch, "Neugrad Watch" },
	{ LocationName::NimaltenCity, "Nimalten City" },
	{ LocationName::NorthKeep, "North Keep" },
	{ LocationName::Oakwood, "Oakwood" },
	{ LocationName::PargranVillage, "Pargran Village" },
	{ LocationName::ReichCorigate, "Reich Corigate" },
	{ LocationName::Riften, "Riften" },
	{ LocationName::Riverwood, "Riverwood" },
	{ LocationName::Snowhawk, "Snowhawk" },
	{ LocationName::Solitude, "Solitude" },
	{ LocationName::Stonehills, "Stonehills" },
	{ LocationName::Sunguard, "Sunguard" },
	{ LocationName::VernimWood, "Vernim Wood" },
	{ LocationName::Whiterun, "Whiterun" },
	{ LocationName::Windhelm, "Windhelm" },
	{ LocationName::Winterhold, "Winterhold" },

	// Summerset Isle.
	{ LocationName::Alinor, "Alinor" },
	{ LocationName::ArchenGrangrove, "Archen Grangrove" },
	{ LocationName::BelportRun, "Belport Run" },
	{ LocationName::Cloudrest, "Cloudrest" },
	{ LocationName::CorgradWastes, "Corgrad Wastes" },
	{ LocationName::Dusk, "Dusk" },
	{ LocationName::EbonStadmont, "Ebon Stadmont" },
	{ LocationName::FirstHold, "First Hold" },
	{ LocationName::Glenview, "Glenview" },
	{ LocationName::GraddunSpring, "Graddun Spring" },
	{ LocationName::HollyFalls, "Holly Falls" },
	{ LocationName::KarndarWatch, "Karndar Watch" },
	{ LocationName::KarnwastenMoor, "Karnwasten Moor" },
	{ LocationName::KingsHaven, "Kings Haven" },
	{ LocationName::Lillandril, "Lillandril" },
	{ LocationName::MarbrukBrook, "Marbruk Brook" },
	{ LocationName::MarnorKeep, "Marnor Keep" },
	{ LocationName::OldFalls, "Old Falls" },
	{ LocationName::Riverfield, "Riverfield" },
	{ LocationName::Riverwatch, "Riverwatch" },
	{ LocationName::Rosefield, "Rosefield" },
	{ LocationName::SeaKeep, "Sea Keep" },
	{ LocationName::Shimmerene, "Shimmerene" },
	{ LocationName::SilsailenPoint, "Silsailen Point" },
	{ LocationName::SilverWood, "Silver Wood" },
	{ LocationName::Skywatch, "Skywatch" },
	{ LocationName::Sunhold, "Sunhold" },
	{ LocationName::ThorheimGuard, "Thorheim Guard" },
	{ LocationName::VulkhelGuard, "Vulkhel Guard" },
	{ LocationName::WastenCoridale, "Wasten Coridale" },
	{ LocationName::WestGuard, "West Guard" },
	{ LocationName::WhiteGuard, "White Guard" },

	// Valenwood.
	{ LocationName::ArchenCormount, "Archen Cormount" },
	{ LocationName::Arenthia, "Arenthia" },
	{ LocationName::BlackPark, "Black Park" },
	{ LocationName::CoriSilmoor, "Cori Silmoor" },
	{ LocationName::CormeirSpring, "Cormeir Spring" },
	{ LocationName::EagleVale, "Eagle Vale" },
	{ LocationName::EbonRo, "Ebon Ro" },
	{ LocationName::Eldenroot, "Eldenroot" },
	{ LocationName::EmperorsRun, "Emperors Run" },
	{ LocationName::Falinesti, "Falinesti" },
	{ LocationName::Glenpoint2, "Glenpoint" },
	{ LocationName::GreenHall, "Green Hall" },
	{ LocationName::Greenheart, "Greenheart" },
	{ LocationName::Haven, "Haven" },
	{ LocationName::HeimdarCity, "Heimdar City" },
	{ LocationName::KarthdarSquare, "Karthdar Square" },
	{ LocationName::Longhaven, "Longhaven" },
	{ LocationName::Longvale, "Longvale" },
	{ LocationName::LynpanMarch, "Lynpan March" },
	{ LocationName::MarbrukField, "Marbruk Field" },
	{ LocationName::MeadowRun, "Meadow Run" },
	{ LocationName::Moonmont, "Moonmont" },
	{ LocationName::Silvenar, "Silvenar" },
	{ LocationName::Southpoint, "Southpoint" },
	{ LocationName::StoneFell, "Stone Fell" },
	{ LocationName::Stonesquare, "Stonesquare" },
	{ LocationName::TarlainHeights, "Tarlain Heights" },
	{ LocationName::ThormarKeep, "Thormar Keep" },
	{ LocationName::VulkwastenWood, "Vulkwasten Wood" },
	{ LocationName::VullainHaven, "Vullain Haven" },
	{ LocationName::WastenBrukbrook, "Wasten Brukbrook" },
	{ LocationName::Woodhearth, "Woodhearth" },

	// Main quest.
	{ LocationName::BlackGate, "Black Gate" },
	{ LocationName::CryptOfHearts, "Crypt of Hearts" },
	{ LocationName::CrystalTower, "Crystal Tower" },
	{ LocationName::DagothUr, "Dagoth Ur" },
	{ LocationName::EldenGrove, "Elden Grove" },
	{ LocationName::FangLair, "Fang Lair" },
	{ LocationName::FortressOfIce, "Fortress of Ice" },
	{ LocationName::ImperialPalace, "Imperial Palace" },
	{ LocationName::ImperialDungeons,  "Imperial Dungeons" },
	{ LocationName::Labyrinthian, "Labyrinthian" },
	{ LocationName::MinesOfKhuras, "Mines of Khuras" },
	{ LocationName::Murkwood, "Murkwood" },
	{ LocationName::SelenesWeb, "Selene's Web" },
	{ LocationName::Stonekeep, "Stonekeep" },
	{ LocationName::TempleOfAgamanus, "Temple of Agamanus" },
	{ LocationName::TempleOfMadGod, "Temple of the Mad God" },
	{ LocationName::HallsOfColossus, "Halls of Colossus" },
	{ LocationName::VaultsOfGemin, "Vaults of Gemin" }
};

// Display names for each type of location. It's for things like the greeting 
// message when entering a city.
const auto LocationTypeDisplayNames = std::map<LocationType, std::string>
{
	// Cities.
	{ LocationType::CityState, "City-State" },
	{ LocationType::Town, "Town" },
	{ LocationType::Village, "Village" },

	// Dungeons.
	{ LocationType::Dungeon, "Dungeon" },

	// Main quest.
	{ LocationType::Unique, "Unique" }
};

// The type of each location, like "city-state", "dungeon", etc..
const auto LocationNameTypes = std::map<LocationName, LocationType>
{
	// Black Marsh.
	{ LocationName::AltenCorimont, LocationType::Village },
	{ LocationName::AltenMarkmont, LocationType::Village },
	{ LocationName::AltenMeirhall, LocationType::Village },
	{ LocationName::Archon, LocationType::CityState },
	{ LocationName::Blackrose, LocationType::CityState },
	{ LocationName::Branchgrove, LocationType::Village },
	{ LocationName::Branchmont, LocationType::Village },
	{ LocationName::Chasecreek, LocationType::Village },
	{ LocationName::Chasepoint, LocationType::Village },
	{ LocationName::Gideon, LocationType::CityState },
	{ LocationName::Glenbridge, LocationType::Village },
	{ LocationName::Greenglade, LocationType::Town },
	{ LocationName::Greenspring, LocationType::Town },
	{ LocationName::Helstrom, LocationType::CityState },
	{ LocationName::Lilmoth, LocationType::CityState },
	{ LocationName::Longmont, LocationType::Village },
	{ LocationName::Moonmarch, LocationType::Town },
	{ LocationName::PortdunMont, LocationType::Village },
	{ LocationName::Riverbridge, LocationType::Village },
	{ LocationName::Riverwalk, LocationType::Town },
	{ LocationName::Rockgrove, LocationType::Town },
	{ LocationName::Rockguard, LocationType::Village },
	{ LocationName::Rockpark, LocationType::Town },
	{ LocationName::Rockpoint, LocationType::Village },
	{ LocationName::Rockspring, LocationType::Village },
	{ LocationName::Seafalls, LocationType::Village },
	{ LocationName::Seaspring, LocationType::Town },
	{ LocationName::Soulrest, LocationType::CityState },
	{ LocationName::Stonewastes, LocationType::Village },
	{ LocationName::Stormhold, LocationType::CityState },
	{ LocationName::TenmarWall, LocationType::Town },
	{ LocationName::Thorn, LocationType::CityState },

	// Elsweyr.
	{ LocationName::Alabaster, LocationType::CityState },
	{ LocationName::BlackHeights, LocationType::Village },
	{ LocationName::BrukreichBridge, LocationType::Town },
	{ LocationName::Chasegrove, LocationType::Village },
	{ LocationName::Chasemoor, LocationType::Village },
	{ LocationName::CoriDarglade, LocationType::Village },
	{ LocationName::Corinthe,  LocationType::CityState },
	{ LocationName::DarkarnPlace, LocationType::Village },
	{ LocationName::DarvulkHaven, LocationType::Town },
	{ LocationName::DuncoriWalk, LocationType::Village },
	{ LocationName::Dune, LocationType::CityState },
	{ LocationName::EinMeirvale, LocationType::Town },
	{ LocationName::Greenhall, LocationType::Town },
	{ LocationName::HeimthorMount, LocationType::Village },
	{ LocationName::HelkarnLand, LocationType::Village },
	{ LocationName::KingsWalk, LocationType::Village },
	{ LocationName::MarkgranBrook, LocationType::Village },
	{ LocationName::MeirLynmount, LocationType::Town },
	{ LocationName::NeumarWalk, LocationType::Village },
	{ LocationName::Orcrest, LocationType::CityState },
	{ LocationName::PortneuView, LocationType::Town },
	{ LocationName::Rimmen, LocationType::CityState },
	{ LocationName::Riverhold, LocationType::CityState },
	{ LocationName::RiverKeep, LocationType::Village },
	{ LocationName::Seaplace, LocationType::Town },
	{ LocationName::Senchal, LocationType::CityState },
	{ LocationName::SouthGuard, LocationType::Village },
	{ LocationName::TardornWood, LocationType::Village },
	{ LocationName::TenmarForest, LocationType::Town },
	{ LocationName::Torval, LocationType::CityState },
	{ LocationName::ValleyGuard, LocationType::Village },
	{ LocationName::VerkarthHills, LocationType::Village },

	// Hammerfell.
	{ LocationName::BelkarthGuard, LocationType::Town },
	{ LocationName::Chaseguard, LocationType::Village },
	{ LocationName::Chasetown, LocationType::Village },
	{ LocationName::CliffKeep, LocationType::Village },
	{ LocationName::CortenMont, LocationType::Village },
	{ LocationName::DragonGate, LocationType::Village },
	{ LocationName::DragonGrove, LocationType::Village },
	{ LocationName::Dragonstar, LocationType::CityState },
	{ LocationName::Elinhir, LocationType::CityState },
	{ LocationName::Gilane, LocationType::CityState },
	{ LocationName::Hegathe, LocationType::CityState },
	{ LocationName::HeldornMount, LocationType::Town },
	{ LocationName::KarnverFalls, LocationType::Village },
	{ LocationName::LainebonPlace, LocationType::Town },
	{ LocationName::Lainlyn, LocationType::Village },
	{ LocationName::NimbelMoor, LocationType::Village },
	{ LocationName::NorthHall, LocationType::Town },
	{ LocationName::Rihad, LocationType::CityState },
	{ LocationName::Riverpoint, LocationType::Town },
	{ LocationName::Riverview, LocationType::Village },
	{ LocationName::Roseguard, LocationType::Town },
	{ LocationName::Sentinel, LocationType::CityState },
	{ LocationName::Shadymarch, LocationType::Village },
	{ LocationName::Skaven, LocationType::CityState },
	{ LocationName::Stonedale, LocationType::Village },
	{ LocationName::Stonemoor, LocationType::Village },
	{ LocationName::Sunkeep, LocationType::Town },
	{ LocationName::Taneth, LocationType::CityState },
	{ LocationName::ThorstadPlace, LocationType::Village },
	{ LocationName::VerkarthCity, LocationType::Village },
	{ LocationName::VulkneuTown, LocationType::Village },
	{ LocationName::VulnimGate, LocationType::Town },

	// High Rock.
	{ LocationName::BlackWastes, LocationType::Village },
	{ LocationName::Camlorn, LocationType::CityState },
	{ LocationName::CloudSpring, LocationType::Town },
	{ LocationName::Daggerfall, LocationType::CityState },
	{ LocationName::DunkarnHaven, LocationType::Village },
	{ LocationName::DunlainFalls, LocationType::Village },
	{ LocationName::EagleBrook, LocationType::Village },
	{ LocationName::EbonWastes, LocationType::Village },
	{ LocationName::Evermore, LocationType::CityState },
	{ LocationName::Farrun, LocationType::CityState },
	{ LocationName::Glenpoint, LocationType::Village },
	{ LocationName::IlessenHills, LocationType::Town },
	{ LocationName::Jehanna, LocationType::CityState },
	{ LocationName::KarthgranVale, LocationType::Village },
	{ LocationName::KingsGuard, LocationType::Town },
	{ LocationName::MarkwastenMoor, LocationType::Village },
	{ LocationName::MeirDarguard, LocationType::Town },
	{ LocationName::MeirThorvale, LocationType::Village },
	{ LocationName::Moonguard, LocationType::Village },
	{ LocationName::NormarHeights, LocationType::Village },
	{ LocationName::NorthPoint, LocationType::CityState },
	{ LocationName::NorvulkHills, LocationType::Village },
	{ LocationName::OldGate, LocationType::Town },
	{ LocationName::PortdunCreek, LocationType::Town },
	{ LocationName::RavenSpring, LocationType::Town },
	{ LocationName::ReichGradkeep, LocationType::Village },
	{ LocationName::Shornhelm, LocationType::CityState },
	{ LocationName::ThorkanPark, LocationType::Village },
	{ LocationName::VermeirWastes, LocationType::Town },
	{ LocationName::Wayrest, LocationType::CityState },
	{ LocationName::WhiteHaven, LocationType::Village },
	{ LocationName::WindKeep, LocationType::Village },

	// Imperial Province. Interestingly, the game dodges this one city's definition, 
	// saying only that "You have arrived in the Imperial City". The map gives a typo.
	{ LocationName::ImperialCity, LocationType::CityState },

	// Morrowind.
	{ LocationName::AmberForest, LocationType::Village },
	{ LocationName::Blacklight, LocationType::CityState },
	{ LocationName::CorkarthRun, LocationType::Village },
	{ LocationName::CormarView, LocationType::Village },
	{ LocationName::DarnimWatch, LocationType::Village },
	{ LocationName::DragonGlade, LocationType::Town },
	{ LocationName::EagleMoor, LocationType::Town },
	{ LocationName::Ebonheart, LocationType::CityState },
	{ LocationName::Firewatch, LocationType::CityState },
	{ LocationName::GlenHaven, LocationType::Town },
	{ LocationName::Greenheights, LocationType::Village },
	{ LocationName::HeimlynKeep, LocationType::Village },
	{ LocationName::HelnimWall, LocationType::Village },
	{ LocationName::KarththorDale, LocationType::Town },
	{ LocationName::KarththorHeights, LocationType::Village },
	{ LocationName::Kragenmoor, LocationType::CityState },
	{ LocationName::MarkgranForest, LocationType::Village },
	{ LocationName::Mournhold, LocationType::CityState },
	{ LocationName::Narsis, LocationType::CityState },
	{ LocationName::Necrom, LocationType::CityState },
	{ LocationName::Oaktown, LocationType::Town },
	{ LocationName::OldKeep, LocationType::Village },
	{ LocationName::OldRun, LocationType::Village },
	{ LocationName::ReichParkeep, LocationType::Village },
	{ LocationName::Riverbridge2, LocationType::Village },
	{ LocationName::SailenVulgate, LocationType::Village },
	{ LocationName::SilgradTower, LocationType::Town },
	{ LocationName::SilnimDale, LocationType::Town },
	{ LocationName::Stonefalls, LocationType::Village },
	{ LocationName::Stoneforest, LocationType::Town },
	{ LocationName::Tear, LocationType::CityState },
	{ LocationName::VerarchenHall, LocationType::Village },

	// Skyrim.
	{ LocationName::AmberGuard, LocationType::Village },
	{ LocationName::Amol, LocationType::Town },
	{ LocationName::BlackMoor, LocationType::Village },
	{ LocationName::Dawnstar, LocationType::CityState },
	{ LocationName::DragonBridge, LocationType::Town },
	{ LocationName::DragonWood, LocationType::Village },
	{ LocationName::DunparWall, LocationType::Village },
	{ LocationName::DunstadGrove, LocationType::Village },
	{ LocationName::Falcrenth, LocationType::CityState },
	{ LocationName::Granitehall, LocationType::Town },
	{ LocationName::Greenwall, LocationType::Village },
	{ LocationName::HelarchenCreek, LocationType::Village },
	{ LocationName::KarthwastenHall, LocationType::Town },
	{ LocationName::Lainalten, LocationType::Village },
	{ LocationName::LaintarDale, LocationType::Village },
	{ LocationName::MarkarthSide, LocationType::Village },
	{ LocationName::NeugradWatch, LocationType::Village },
	{ LocationName::NimaltenCity, LocationType::Village },
	{ LocationName::NorthKeep, LocationType::Village },
	{ LocationName::Oakwood, LocationType::Town },
	{ LocationName::PargranVillage, LocationType::Village },
	{ LocationName::ReichCorigate, LocationType::Village },
	{ LocationName::Riften, LocationType::CityState },
	{ LocationName::Riverwood, LocationType::Village },
	{ LocationName::Snowhawk, LocationType::CityState },
	{ LocationName::Solitude, LocationType::CityState },
	{ LocationName::Stonehills, LocationType::Town },
	{ LocationName::Sunguard, LocationType::Town },
	{ LocationName::VernimWood, LocationType::Town },
	{ LocationName::Whiterun, LocationType::CityState },
	{ LocationName::Windhelm, LocationType::CityState },
	{ LocationName::Winterhold, LocationType::CityState },

	// Summerset Isle.
	{ LocationName::Alinor, LocationType::CityState },
	{ LocationName::ArchenGrangrove, LocationType::Town },
	{ LocationName::BelportRun, LocationType::Town },
	{ LocationName::Cloudrest, LocationType::CityState },
	{ LocationName::CorgradWastes, LocationType::Town },
	{ LocationName::Dusk, LocationType::CityState },
	{ LocationName::EbonStadmont, LocationType::Village },
	{ LocationName::FirstHold, LocationType::CityState },
	{ LocationName::Glenview, LocationType::Village },
	{ LocationName::GraddunSpring, LocationType::Village },
	{ LocationName::HollyFalls, LocationType::Village },
	{ LocationName::KarndarWatch, LocationType::Village },
	{ LocationName::KarnwastenMoor, LocationType::Village },
	{ LocationName::KingsHaven, LocationType::Village },
	{ LocationName::Lillandril, LocationType::CityState },
	{ LocationName::MarbrukBrook, LocationType::Village },
	{ LocationName::MarnorKeep, LocationType::Town },
	{ LocationName::OldFalls, LocationType::Village },
	{ LocationName::Riverfield, LocationType::Town },
	{ LocationName::Riverwatch, LocationType::Village },
	{ LocationName::Rosefield, LocationType::Village },
	{ LocationName::SeaKeep, LocationType::Town },
	{ LocationName::Shimmerene, LocationType::CityState },
	{ LocationName::SilsailenPoint, LocationType::Village },
	{ LocationName::SilverWood, LocationType::Village },
	{ LocationName::Skywatch, LocationType::CityState },
	{ LocationName::Sunhold, LocationType::CityState },
	{ LocationName::ThorheimGuard, LocationType::Village },
	{ LocationName::VulkhelGuard, LocationType::Town },
	{ LocationName::WastenCoridale, LocationType::Village },
	{ LocationName::WestGuard, LocationType::Town },
	{ LocationName::WhiteGuard, LocationType::Village },

	// Valenwood.
	{ LocationName::ArchenCormount, LocationType::Village },
	{ LocationName::Arenthia, LocationType::CityState },
	{ LocationName::BlackPark, LocationType::Village },
	{ LocationName::CoriSilmoor, LocationType::Village },
	{ LocationName::CormeirSpring, LocationType::Village },
	{ LocationName::EagleVale, LocationType::Town },
	{ LocationName::EbonRo, LocationType::Village },
	{ LocationName::Eldenroot, LocationType::CityState },
	{ LocationName::EmperorsRun, LocationType::Town },
	{ LocationName::Falinesti, LocationType::CityState },
	{ LocationName::Glenpoint2, LocationType::Village },
	{ LocationName::GreenHall, LocationType::Village },
	{ LocationName::Greenheart, LocationType::CityState },
	{ LocationName::Haven, LocationType::CityState },
	{ LocationName::HeimdarCity, LocationType::Village },
	{ LocationName::KarthdarSquare, LocationType::Town },
	{ LocationName::Longhaven, LocationType::Town },
	{ LocationName::Longvale, LocationType::Town },
	{ LocationName::LynpanMarch, LocationType::Village },
	{ LocationName::MarbrukField, LocationType::Village },
	{ LocationName::MeadowRun, LocationType::Village },
	{ LocationName::Moonmont, LocationType::Village },
	{ LocationName::Silvenar, LocationType::CityState },
	{ LocationName::Southpoint, LocationType::CityState },
	{ LocationName::StoneFell, LocationType::Village },
	{ LocationName::Stonesquare, LocationType::Village },
	{ LocationName::TarlainHeights, LocationType::Village },
	{ LocationName::ThormarKeep, LocationType::Town },
	{ LocationName::VulkwastenWood, LocationType::Town },
	{ LocationName::VullainHaven, LocationType::Village },
	{ LocationName::WastenBrukbrook, LocationType::Town },
	{ LocationName::Woodhearth, LocationType::CityState },

	// Main quest.
	{ LocationName::BlackGate, LocationType::Dungeon },
	{ LocationName::CryptOfHearts, LocationType::Unique },
	{ LocationName::CrystalTower, LocationType::Unique },
	{ LocationName::DagothUr, LocationType::Unique },
	{ LocationName::EldenGrove, LocationType::Unique },
	{ LocationName::FangLair, LocationType::Unique },
	{ LocationName::FortressOfIce, LocationType::Dungeon },
	{ LocationName::ImperialPalace, LocationType::Unique },
	{ LocationName::ImperialDungeons,  LocationType::Unique },
	{ LocationName::Labyrinthian, LocationType::Unique },
	{ LocationName::MinesOfKhuras, LocationType::Dungeon },
	{ LocationName::Murkwood, LocationType::Unique },
	{ LocationName::SelenesWeb, LocationType::Dungeon },
	{ LocationName::Stonekeep, LocationType::Dungeon },
	{ LocationName::TempleOfAgamanus, LocationType::Dungeon },
	{ LocationName::TempleOfMadGod, LocationType::Dungeon },
	{ LocationName::HallsOfColossus, LocationType::Unique },
	{ LocationName::VaultsOfGemin, LocationType::Dungeon }
};

// Each location has a climate.
const auto LocationClimates = std::map<LocationName, ClimateName>
{
	// Black Marsh. An awful lot of these locations have "dark ground" with rain,
	// and some deserts have fog. I think foggy deserts are unique to Black Marsh.
	{ LocationName::AltenCorimont, ClimateName::Grassy },
	{ LocationName::AltenMarkmont, ClimateName::Grassy },
	{ LocationName::AltenMeirhall, ClimateName::Desert },
	{ LocationName::Archon, ClimateName::Desert },
	{ LocationName::Blackrose, ClimateName::Desert },
	{ LocationName::Branchgrove, ClimateName::Desert },
	{ LocationName::Branchmont, ClimateName::Grassy },
	{ LocationName::Chasecreek, ClimateName::Grassy },
	{ LocationName::Chasepoint, ClimateName::Desert },
	{ LocationName::Gideon, ClimateName::Grassy },
	{ LocationName::Glenbridge, ClimateName::Grassy },
	{ LocationName::Greenglade, ClimateName::Grassy },
	{ LocationName::Greenspring, ClimateName::Grassy },
	{ LocationName::Helstrom, ClimateName::Grassy },
	{ LocationName::Lilmoth, ClimateName::Desert },
	{ LocationName::Longmont, ClimateName::Desert },
	{ LocationName::Moonmarch, ClimateName::Desert },
	{ LocationName::PortdunMont, ClimateName::Desert },
	{ LocationName::Riverbridge, ClimateName::Grassy },
	{ LocationName::Riverwalk, ClimateName::Grassy },
	{ LocationName::Rockgrove, ClimateName::Desert },
	{ LocationName::Rockguard, ClimateName::Grassy },
	{ LocationName::Rockpark, ClimateName::Desert },
	{ LocationName::Rockpoint, ClimateName::Grassy },
	{ LocationName::Rockspring, ClimateName::Desert },
	{ LocationName::Seafalls, ClimateName::Desert },
	{ LocationName::Seaspring, ClimateName::Desert },
	{ LocationName::Soulrest, ClimateName::Desert },
	{ LocationName::Stonewastes, ClimateName::Desert },
	{ LocationName::Stormhold, ClimateName::Grassy },
	{ LocationName::TenmarWall, ClimateName::Grassy },
	{ LocationName::Thorn, ClimateName::Grassy },

	// Elsweyr. I expected Elsweyr to have something other than 100% grass.
	// The "Sands of Elsweyr", anyone?
	{ LocationName::Alabaster, ClimateName::Grassy },
	{ LocationName::BlackHeights, ClimateName::Grassy },
	{ LocationName::BrukreichBridge, ClimateName::Grassy },
	{ LocationName::Chasegrove, ClimateName::Grassy },
	{ LocationName::Chasemoor, ClimateName::Grassy },
	{ LocationName::CoriDarglade, ClimateName::Grassy },
	{ LocationName::Corinthe,  ClimateName::Grassy },
	{ LocationName::DarkarnPlace, ClimateName::Grassy },
	{ LocationName::DarvulkHaven, ClimateName::Grassy },
	{ LocationName::DuncoriWalk, ClimateName::Grassy },
	{ LocationName::Dune, ClimateName::Grassy },
	{ LocationName::EinMeirvale, ClimateName::Grassy },
	{ LocationName::Greenhall, ClimateName::Grassy },
	{ LocationName::HeimthorMount, ClimateName::Grassy },
	{ LocationName::HelkarnLand, ClimateName::Grassy },
	{ LocationName::KingsWalk, ClimateName::Grassy },
	{ LocationName::MarkgranBrook, ClimateName::Grassy },
	{ LocationName::MeirLynmount, ClimateName::Grassy },
	{ LocationName::NeumarWalk, ClimateName::Grassy },
	{ LocationName::Orcrest, ClimateName::Grassy },
	{ LocationName::PortneuView, ClimateName::Grassy },
	{ LocationName::Rimmen, ClimateName::Grassy },
	{ LocationName::Riverhold, ClimateName::Grassy },
	{ LocationName::RiverKeep, ClimateName::Grassy },
	{ LocationName::Seaplace, ClimateName::Grassy },
	{ LocationName::Senchal, ClimateName::Grassy },
	{ LocationName::SouthGuard, ClimateName::Grassy },
	{ LocationName::TardornWood, ClimateName::Grassy },
	{ LocationName::TenmarForest, ClimateName::Grassy },
	{ LocationName::Torval, ClimateName::Grassy },
	{ LocationName::ValleyGuard, ClimateName::Grassy },
	{ LocationName::VerkarthHills, ClimateName::Grassy },

	// Hammerfell. This province seems to have some of everything.
	{ LocationName::BelkarthGuard, ClimateName::Snowy },
	{ LocationName::Chaseguard, ClimateName::Desert },
	{ LocationName::Chasetown, ClimateName::Cold },
	{ LocationName::CliffKeep, ClimateName::Desert },
	{ LocationName::CortenMont, ClimateName::Desert },
	{ LocationName::DragonGate, ClimateName::Desert },
	{ LocationName::DragonGrove, ClimateName::Grassy },
	{ LocationName::Dragonstar, ClimateName::Cold },
	{ LocationName::Elinhir, ClimateName::Cold },
	{ LocationName::Gilane, ClimateName::Desert },
	{ LocationName::Hegathe, ClimateName::Grassy },
	{ LocationName::HeldornMount, ClimateName::Desert },
	{ LocationName::KarnverFalls, ClimateName::Desert },
	{ LocationName::LainebonPlace, ClimateName::Desert },
	{ LocationName::Lainlyn, ClimateName::Grassy },
	{ LocationName::NimbelMoor, ClimateName::Cold },
	{ LocationName::NorthHall, ClimateName::Desert },
	{ LocationName::Rihad, ClimateName::Desert },
	{ LocationName::Riverpoint, ClimateName::Desert },
	{ LocationName::Riverview, ClimateName::Desert },
	{ LocationName::Roseguard, ClimateName::Desert },
	{ LocationName::Sentinel, ClimateName::Cold },
	{ LocationName::Shadymarch, ClimateName::Desert },
	{ LocationName::Skaven, ClimateName::Desert },
	{ LocationName::Stonedale, ClimateName::Desert },
	{ LocationName::Stonemoor, ClimateName::Desert },
	{ LocationName::Sunkeep, ClimateName::Grassy },
	{ LocationName::Taneth, ClimateName::Desert },
	{ LocationName::ThorstadPlace, ClimateName::Cold },
	{ LocationName::VerkarthCity, ClimateName::Desert },
	{ LocationName::VulkneuTown, ClimateName::Desert },
	{ LocationName::VulnimGate, ClimateName::Desert },

	// High Rock. Some places that are cold/snowy are also foggy.
	{ LocationName::BlackWastes, ClimateName::Snowy },
	{ LocationName::Camlorn, ClimateName::Cold },
	{ LocationName::CloudSpring, ClimateName::Cold },
	{ LocationName::Daggerfall, ClimateName::Grassy },
	{ LocationName::DunkarnHaven, ClimateName::Cold },
	{ LocationName::DunlainFalls, ClimateName::Snowy },
	{ LocationName::EagleBrook, ClimateName::Snowy },
	{ LocationName::EbonWastes, ClimateName::Cold },
	{ LocationName::Evermore, ClimateName::Snowy },
	{ LocationName::Farrun, ClimateName::Snowy },
	{ LocationName::Glenpoint, ClimateName::Cold },
	{ LocationName::IlessenHills, ClimateName::Cold },
	{ LocationName::Jehanna, ClimateName::Snowy },
	{ LocationName::KarthgranVale, ClimateName::Snowy },
	{ LocationName::KingsGuard, ClimateName::Cold },
	{ LocationName::MarkwastenMoor, ClimateName::Snowy },
	{ LocationName::MeirDarguard, ClimateName::Snowy },
	{ LocationName::MeirThorvale, ClimateName::Snowy },
	{ LocationName::Moonguard, ClimateName::Cold },
	{ LocationName::NormarHeights, ClimateName::Snowy },
	{ LocationName::NorthPoint, ClimateName::Snowy },
	{ LocationName::NorvulkHills, ClimateName::Cold },
	{ LocationName::OldGate, ClimateName::Snowy },
	{ LocationName::PortdunCreek, ClimateName::Snowy },
	{ LocationName::RavenSpring, ClimateName::Snowy },
	{ LocationName::ReichGradkeep, ClimateName::Grassy },
	{ LocationName::Shornhelm, ClimateName::Cold },
	{ LocationName::ThorkanPark, ClimateName::Cold },
	{ LocationName::VermeirWastes, ClimateName::Cold },
	{ LocationName::Wayrest, ClimateName::Cold },
	{ LocationName::WhiteHaven, ClimateName::Cold },
	{ LocationName::WindKeep, ClimateName::Cold },

	// Imperial Province.
	{ LocationName::ImperialCity, ClimateName::Grassy },

	// Morrowind. The distant volcano seems to correctly align with the compass
	// and the current map location. Some grassy places can be foggy.
	{ LocationName::AmberForest, ClimateName::Grassy },
	{ LocationName::Blacklight, ClimateName::Snowy },
	{ LocationName::CorkarthRun, ClimateName::Grassy },
	{ LocationName::CormarView, ClimateName::Snowy },
	{ LocationName::DarnimWatch, ClimateName::Cold },
	{ LocationName::DragonGlade, ClimateName::Snowy },
	{ LocationName::EagleMoor, ClimateName::Grassy },
	{ LocationName::Ebonheart, ClimateName::Grassy },
	{ LocationName::Firewatch, ClimateName::Snowy },
	{ LocationName::GlenHaven, ClimateName::Snowy },
	{ LocationName::Greenheights, ClimateName::Snowy },
	{ LocationName::HeimlynKeep, ClimateName::Grassy },
	{ LocationName::HelnimWall, ClimateName::Snowy },
	{ LocationName::KarththorDale, ClimateName::Cold },
	{ LocationName::KarththorHeights, ClimateName::Snowy },
	{ LocationName::Kragenmoor, ClimateName::Grassy },
	{ LocationName::MarkgranForest, ClimateName::Cold },
	{ LocationName::Mournhold, ClimateName::Grassy },
	{ LocationName::Narsis, ClimateName::Grassy },
	{ LocationName::Necrom, ClimateName::Cold },
	{ LocationName::Oaktown, ClimateName::Grassy },
	{ LocationName::OldKeep, ClimateName::Grassy },
	{ LocationName::OldRun, ClimateName::Snowy },
	{ LocationName::ReichParkeep, ClimateName::Snowy },
	{ LocationName::Riverbridge2, ClimateName::Grassy },
	{ LocationName::SailenVulgate, ClimateName::Cold },
	{ LocationName::SilgradTower, ClimateName::Snowy },
	{ LocationName::SilnimDale, ClimateName::Grassy },
	{ LocationName::Stonefalls, ClimateName::Cold },
	{ LocationName::Stoneforest, ClimateName::Snowy },
	{ LocationName::Tear, ClimateName::Grassy },
	{ LocationName::VerarchenHall, ClimateName::Snowy },

	// Skyrim. Snowy places can also be foggy with the snow music. Some cold
	// places have clear weather with sunny music.
	{ LocationName::AmberGuard, ClimateName::Snowy },
	{ LocationName::Amol, ClimateName::Snowy },
	{ LocationName::BlackMoor, ClimateName::Cold },
	{ LocationName::Dawnstar, ClimateName::Snowy },
	{ LocationName::DragonBridge, ClimateName::Snowy },
	{ LocationName::DragonWood, ClimateName::Cold },
	{ LocationName::DunparWall, ClimateName::Cold },
	{ LocationName::DunstadGrove, ClimateName::Cold },
	{ LocationName::Falcrenth, ClimateName::Cold },
	{ LocationName::Granitehall, ClimateName::Cold },
	{ LocationName::Greenwall, ClimateName::Cold },
	{ LocationName::HelarchenCreek, ClimateName::Cold },
	{ LocationName::KarthwastenHall, ClimateName::Snowy },
	{ LocationName::Lainalten, ClimateName::Snowy },
	{ LocationName::LaintarDale, ClimateName::Snowy },
	{ LocationName::MarkarthSide, ClimateName::Snowy },
	{ LocationName::NeugradWatch, ClimateName::Cold },
	{ LocationName::NimaltenCity, ClimateName::Cold },
	{ LocationName::NorthKeep, ClimateName::Cold },
	{ LocationName::Oakwood, ClimateName::Cold },
	{ LocationName::PargranVillage, ClimateName::Snowy },
	{ LocationName::ReichCorigate, ClimateName::Cold },
	{ LocationName::Riften, ClimateName::Cold },
	{ LocationName::Riverwood, ClimateName::Cold },
	{ LocationName::Snowhawk, ClimateName::Snowy },
	{ LocationName::Solitude, ClimateName::Snowy },
	{ LocationName::Stonehills, ClimateName::Snowy },
	{ LocationName::Sunguard, ClimateName::Cold },
	{ LocationName::VernimWood, ClimateName::Cold },
	{ LocationName::Whiterun, ClimateName::Cold },
	{ LocationName::Windhelm, ClimateName::Snowy },
	{ LocationName::Winterhold, ClimateName::Snowy },

	// Summerset Isle. Every location is the grassy climate.
	{ LocationName::Alinor, ClimateName::Grassy },
	{ LocationName::ArchenGrangrove, ClimateName::Grassy },
	{ LocationName::BelportRun, ClimateName::Grassy },
	{ LocationName::Cloudrest, ClimateName::Grassy },
	{ LocationName::CorgradWastes, ClimateName::Grassy },
	{ LocationName::Dusk, ClimateName::Grassy },
	{ LocationName::EbonStadmont, ClimateName::Grassy },
	{ LocationName::FirstHold, ClimateName::Grassy },
	{ LocationName::Glenview, ClimateName::Grassy },
	{ LocationName::GraddunSpring, ClimateName::Grassy },
	{ LocationName::HollyFalls, ClimateName::Grassy },
	{ LocationName::KarndarWatch, ClimateName::Grassy },
	{ LocationName::KarnwastenMoor, ClimateName::Grassy },
	{ LocationName::KingsHaven, ClimateName::Grassy },
	{ LocationName::Lillandril, ClimateName::Grassy },
	{ LocationName::MarbrukBrook, ClimateName::Grassy },
	{ LocationName::MarnorKeep, ClimateName::Grassy },
	{ LocationName::OldFalls, ClimateName::Grassy },
	{ LocationName::Riverfield, ClimateName::Grassy },
	{ LocationName::Riverwatch, ClimateName::Grassy },
	{ LocationName::Rosefield, ClimateName::Grassy },
	{ LocationName::SeaKeep, ClimateName::Grassy },
	{ LocationName::Shimmerene, ClimateName::Grassy },
	{ LocationName::SilsailenPoint, ClimateName::Grassy },
	{ LocationName::SilverWood, ClimateName::Grassy },
	{ LocationName::Skywatch, ClimateName::Grassy },
	{ LocationName::Sunhold, ClimateName::Grassy },
	{ LocationName::ThorheimGuard, ClimateName::Grassy },
	{ LocationName::VulkhelGuard, ClimateName::Grassy },
	{ LocationName::WastenCoridale, ClimateName::Grassy },
	{ LocationName::WestGuard, ClimateName::Grassy },
	{ LocationName::WhiteGuard, ClimateName::Grassy },

	// Valenwood. Some of the grassy places can be foggy during some seasons.
	{ LocationName::ArchenCormount, ClimateName::Grassy },
	{ LocationName::Arenthia, ClimateName::Cold },
	{ LocationName::BlackPark, ClimateName::Grassy },
	{ LocationName::CoriSilmoor, ClimateName::Grassy },
	{ LocationName::CormeirSpring, ClimateName::Grassy },
	{ LocationName::EagleVale, ClimateName::Grassy },
	{ LocationName::EbonRo, ClimateName::Cold },
	{ LocationName::Eldenroot, ClimateName::Grassy },
	{ LocationName::EmperorsRun, ClimateName::Grassy },
	{ LocationName::Falinesti, ClimateName::Grassy },
	{ LocationName::Glenpoint2, ClimateName::Grassy },
	{ LocationName::GreenHall, ClimateName::Grassy },
	{ LocationName::Greenheart, ClimateName::Grassy },
	{ LocationName::Haven, ClimateName::Grassy },
	{ LocationName::HeimdarCity, ClimateName::Grassy },
	{ LocationName::KarthdarSquare, ClimateName::Grassy },
	{ LocationName::Longhaven, ClimateName::Grassy },
	{ LocationName::Longvale, ClimateName::Grassy },
	{ LocationName::LynpanMarch, ClimateName::Grassy },
	{ LocationName::MarbrukField, ClimateName::Grassy },
	{ LocationName::MeadowRun, ClimateName::Grassy },
	{ LocationName::Moonmont, ClimateName::Grassy },
	{ LocationName::Silvenar, ClimateName::Grassy },
	{ LocationName::Southpoint, ClimateName::Grassy },
	{ LocationName::StoneFell, ClimateName::Grassy },
	{ LocationName::Stonesquare, ClimateName::Grassy },
	{ LocationName::TarlainHeights, ClimateName::Grassy },
	{ LocationName::ThormarKeep, ClimateName::Grassy },
	{ LocationName::VulkwastenWood, ClimateName::Grassy },
	{ LocationName::VullainHaven, ClimateName::Grassy },
	{ LocationName::WastenBrukbrook, ClimateName::Grassy },
	{ LocationName::Woodhearth, ClimateName::Grassy },

	// Main quest. None of these climates should really be used. They are all interiors.
	// Should there be an "Interior" climate? It's basically the absence of climate.
	{ LocationName::BlackGate, ClimateName::Grassy },
	{ LocationName::CryptOfHearts, ClimateName::Cold },
	{ LocationName::CrystalTower, ClimateName::Grassy },
	{ LocationName::DagothUr, ClimateName::Grassy },
	{ LocationName::EldenGrove, ClimateName::Grassy },
	{ LocationName::FangLair, ClimateName::Desert },
	{ LocationName::FortressOfIce, ClimateName::Snowy },
	{ LocationName::ImperialPalace, ClimateName::Grassy },
	{ LocationName::ImperialDungeons,  ClimateName::Grassy },
	{ LocationName::Labyrinthian, ClimateName::Snowy },
	{ LocationName::MinesOfKhuras, ClimateName::Cold },
	{ LocationName::Murkwood, ClimateName::Grassy },
	{ LocationName::SelenesWeb, ClimateName::Grassy },
	{ LocationName::Stonekeep, ClimateName::Desert },
	{ LocationName::TempleOfAgamanus, ClimateName::Desert },
	{ LocationName::TempleOfMadGod, ClimateName::Grassy },
	{ LocationName::HallsOfColossus, ClimateName::Grassy },
	{ LocationName::VaultsOfGemin, ClimateName::Grassy }
};

Location::Location(LocationName locationName)
{
	this->locationName = locationName;
}

Location::~Location()
{

}

std::vector<LocationName> Location::getAllLocations()
{
	auto locations = std::vector<LocationName>();
	for (const auto &item : LocationNameTypes)
	{
		locations.push_back(item.first);
	}

	assert(locations.size() > 0);
	return locations;
}

const LocationName &Location::getLocationName() const
{
	return this->locationName;
}

LocationType Location::getLocationType() const
{	
	auto locationType = LocationNameTypes.at(this->getLocationName());
	return locationType;
}

ClimateName Location::getClimateName() const
{
	auto climateName = LocationClimates.at(this->getLocationName());
	return climateName;
}

std::string Location::toString() const
{
	auto displayName = LocationDisplayNames.at(this->getLocationName());
	assert(displayName.size() > 0);
	return displayName;
}

std::string Location::typeToString() const
{
	auto displayName = LocationTypeDisplayNames.at(this->getLocationType());
	assert(displayName.size() > 0);
	return displayName;
}
